name: slameckacz
version: '0.1.0.0'
license: UnspecifiedLicense
ghc-options:
- -threaded
- -fwarn-unused-binds
- -fwarn-unused-imports
dependencies:
- base ==4.*
- hakyll ==4.12.*
- hakyll-sass
- filepath
- containers
executables:
  site:
    main: site.hs
